ALTER TYPE "OperationEventType" ADD VALUE IF NOT EXISTS 'PROPERTY_UPDATED';
ALTER TYPE "OperationEventType" ADD VALUE IF NOT EXISTS 'PROPERTY_PUBLISHED';
ALTER TYPE "OperationEventType" ADD VALUE IF NOT EXISTS 'PROPERTY_UNPUBLISHED';
ALTER TYPE "OperationEventType" ADD VALUE IF NOT EXISTS 'STUDIO_JOB_COMPLETED';
ALTER TYPE "OperationEventType" ADD VALUE IF NOT EXISTS 'WEBSITE_SYNC_FAILED';
ALTER TYPE "OperationEventType" ADD VALUE IF NOT EXISTS 'WHATSAPP_DISCONNECTED';
ALTER TYPE "OperationEventType" ADD VALUE IF NOT EXISTS 'CALENDAR_SYNC_FAILED';
