import type { DeedCaseType } from './types';

export const DEED_PROCESS_CATEGORIES = [
  'TRANSFER',
  'SECURITY',
  'INHERITANCE',
  'REGISTRATION',
  'SPECIAL',
] as const;

export type DeedProcessCategory = (typeof DEED_PROCESS_CATEGORIES)[number];

export const deedProcessCategoryLabels: Record<DeedProcessCategory, string> = {
  TRANSFER: 'Satış ve devir',
  SECURITY: 'İpotek ve haklar',
  INHERITANCE: 'Miras ve paylaşım',
  REGISTRATION: 'Tescil ve yapı',
  SPECIAL: 'Özel işlemler',
};

export type DeedProcessGuide = {
  id: string;
  title: string;
  shortTitle: string;
  description: string;
  category: DeedProcessCategory;
  caseType: DeedCaseType;
  duration: string;
  audience: string;
  steps: string[];
  documents: string[];
  risks: string[];
  officialAction: string;
};

export const DEED_OPERATION_STAGES = [
  {
    id: 'authority',
    number: '01',
    title: 'Yetki ve kimlik',
    description: 'Malik, taraflar ve temsil yetkisi doğrulanır.',
  },
  {
    id: 'property',
    number: '02',
    title: 'Tapu ve takyidat',
    description: 'Taşınmaz, pay, adres, şerh ve kısıtlar kontrol edilir.',
  },
  {
    id: 'documents',
    number: '03',
    title: 'Evrak hazırlığı',
    description: 'İşleme özel belge, sigorta ve kurum kayıtları tamamlanır.',
  },
  {
    id: 'payment',
    number: '04',
    title: 'Bedel ve masraflar',
    description: 'Gerçek bedel, ödeme planı, harç ve masraflar teyit edilir.',
  },
  {
    id: 'application',
    number: '05',
    title: 'Başvuru ve randevu',
    description: 'Web Tapu başvurusu, SMS, ödeme ve randevu kullanıcıca izlenir.',
  },
  {
    id: 'closing',
    number: '06',
    title: 'İmza ve kapanış',
    description: 'Resmî imza, teslim, arşiv ve işlem sonrası bildirimler kapatılır.',
  },
] as const;

const sharedSaleDocuments = [
  'Güncel tapu kaydı ve takyidat bilgisi',
  'Taraf kimlikleri ve iletişim bilgileri',
  'Varsa temsil veya vekâlet belgesi',
  'Geçerli DASK poliçe bilgisi',
  'Belediye emlak vergisi değeri',
  'Gerçek satış bedeli ve ödeme planı',
];

export const DEED_PROCESS_GUIDES: DeedProcessGuide[] = [
  {
    id: 'standard-sale',
    title: 'Standart taşınmaz satışı',
    shortTitle: 'Satış',
    description: 'Satıcıdan alıcıya konut, iş yeri veya arsa devrini baştan sona hazırlayın.',
    category: 'TRANSFER',
    caseType: 'SALE',
    duration: '6 aşama',
    audience: 'Alıcı + satıcı',
    steps: ['Yetki ve taraf kontrolü', 'Tapu/takyidat incelemesi', 'Bedel ve ödeme mutabakatı', 'Web Tapu hazırlığı', 'Randevu ve imza', 'Teslim ve arşiv'],
    documents: sharedSaleDocuments,
    risks: ['Eksik veya kapsam dışı yetki', 'Takyidat ve aile konutu kısıtı', 'Gerçek bedelden düşük beyan', 'Üçüncü kişi hesabından ödeme'],
    officialAction: 'Başvuru ve tescil yalnız Web Tapu/Tapu Müdürlüğü üzerinden taraf veya yetkili temsilci tarafından tamamlanır.',
  },
  {
    id: 'purchase-follow-up',
    title: 'Alıcı adına satın alma takibi',
    shortTitle: 'Alış',
    description: 'Alıcının finansman, inceleme, teklif ve devir hazırlığını tek dosyada izleyin.',
    category: 'TRANSFER',
    caseType: 'PURCHASE',
    duration: '6 aşama',
    audience: 'Alıcı',
    steps: ['Talep ve bütçe kaydı', 'Taşınmaz incelemesi', 'Teklif ve kabul', 'Finansman/ekspertiz', 'Devir hazırlığı', 'Teslim ve bildirim'],
    documents: ['Alıcı talep formu', 'Satın alma teklif formu', ...sharedSaleDocuments, 'Varsa kredi ve ekspertiz evrakı'],
    risks: ['Finansman koşulunun belirsizliği', 'Proje ile fiilî durum farkı', 'Kiracı veya teslim sorunu', 'Ödeme sahibi ile alıcı uyuşmazlığı'],
    officialAction: 'Resmî tapu kaydı, takyidat ve başvuru alıcı/malik yetkisiyle resmî kanaldan doğrulanır.',
  },
  {
    id: 'donation',
    title: 'Bağış ve hibe yoluyla devir',
    shortTitle: 'Hibe',
    description: 'İvazsız taşınmaz devrinde taraf, vergi ve resmî başvuru hazırlığını yönetin.',
    category: 'TRANSFER',
    caseType: 'OTHER',
    duration: '5 aşama',
    audience: 'Bağışlayan + bağışlanan',
    steps: ['Taraf ve ehliyet kontrolü', 'Taşınmaz/takyidat incelemesi', 'Vergi ve değer hazırlığı', 'Başvuru/randevu', 'Tescil ve arşiv'],
    documents: ['Kimlik ve iletişim bilgileri', 'Güncel tapu kaydı', 'Belediye emlak değeri', 'DASK bilgisi', 'Vergi/harç hazırlık notu'],
    risks: ['Fiil ehliyeti veya irade şüphesi', 'Miras ve muvazaa uyuşmazlığı', 'Vergi yükümlülüğünün yanlış hesaplanması'],
    officialAction: 'Bağış işlemi resmî makam önünde tamamlanır; uygulama bağış sözleşmesi veya resmî senet üretmez.',
  },
  {
    id: 'exchange',
    title: 'Trampa (taşınmaz değişimi)',
    shortTitle: 'Trampa',
    description: 'İki veya daha fazla taşınmazın karşılıklı devrinde değer ve taraf akışını izleyin.',
    category: 'TRANSFER',
    caseType: 'OTHER',
    duration: '6 aşama',
    audience: 'Tüm taraflar',
    steps: ['Taşınmazları eşleştirme', 'Taraf/pay kontrolü', 'Değer farkı ve ödeme', 'Takyidat incelemesi', 'Başvuru ve imza', 'Karşılıklı teslim'],
    documents: ['Her taşınmaz için güncel tapu kaydı', 'Taraf kimlikleri', 'Değer ve fark ödeme mutabakatı', 'DASK ve belediye değerleri'],
    risks: ['Taşınmazlardan birindeki kısıt', 'Değer farkının eksik beyanı', 'Eşzamanlı teslim planının olmaması'],
    officialAction: 'Her taşınmaz bakımından resmî devir ve harç değerlendirmesi ilgili müdürlükçe yapılır.',
  },
  {
    id: 'lifelong-care',
    title: 'Ölünceye kadar bakma karşılığı devir',
    shortTitle: 'Bakma akdi',
    description: 'Bakım borcu karşılığı devir için uzman ve resmî belge hazırlık adımlarını izleyin.',
    category: 'TRANSFER',
    caseType: 'OTHER',
    duration: 'Uzman kontrollü',
    audience: 'Bakım alacaklısı + borçlusu',
    steps: ['Ehliyet/irade kontrolü', 'Sözleşme ve temsil incelemesi', 'Taşınmaz/takyidat', 'Vergi/harç hazırlığı', 'Resmî işlem', 'Arşiv'],
    documents: ['Taraf kimlikleri', 'Uzman onaylı sözleşme/karar', 'Güncel tapu kaydı', 'Sağlık veya ehliyet belgeleri gerekiyorsa resmî nüsha'],
    risks: ['Fiil ehliyeti ve irade', 'Mirasçılarla uyuşmazlık', 'Sözleşme şekli ve kapsamı'],
    officialAction: 'Sözleşme ve tescil için noter, hukuk uzmanı ve Tapu Müdürlüğü yönlendirmesi gerekir.',
  },
  {
    id: 'mortgage-establishment',
    title: 'İpotek tesisi',
    shortTitle: 'İpotek',
    description: 'Kredi veya borç teminatı için ipotek hazırlığını; derece, tutar ve evrakla izleyin.',
    category: 'SECURITY',
    caseType: 'MORTGAGE',
    duration: '5 aşama',
    audience: 'Malik + alacaklı',
    steps: ['Taraf ve temsil', 'Teminat bilgileri', 'Ekspertiz/DASK', 'Kurum yazıları', 'Tescil ve belge kontrolü'],
    documents: ['Banka veya alacaklı talimatı', 'Kredi/borç dayanağı', 'Ekspertiz raporu', 'DASK bilgisi', 'Güncel tapu kaydı'],
    risks: ['Derece/sıra ve tutar hatası', 'Malik ile borçlu ilişkisinin belirsizliği', 'Mevcut takyidatların gözden kaçması'],
    officialAction: 'İpotek ancak resmî tescille kurulur; panel yalnız hazırlık ve takip kaydıdır.',
  },
  {
    id: 'mortgage-release',
    title: 'İpotek terkini',
    shortTitle: 'İpotek kaldırma',
    description: 'Borcu kapanan ipoteğin hak sahibi yazısı ve elektronik terkin sürecini takip edin.',
    category: 'SECURITY',
    caseType: 'MORTGAGE',
    duration: '4 aşama',
    audience: 'Malik + alacaklı kurum',
    steps: ['Borç kapanış teyidi', 'Terkin talimatı', 'Elektronik/resmî gönderim', 'Güncel kayıt doğrulaması'],
    documents: ['Hak sahibi terkin yazısı/talimatı', 'Borcun kapanış kaydı', 'İpotek bilgisi ve yevmiye', 'Güncel tapu kayıt örneği'],
    risks: ['Yanlış ipotek kaydının seçilmesi', 'Yetkisiz veya doğrulanmamış terkin yazısı', 'Kayıttan kalktığı doğrulanmadan dosyanın kapatılması'],
    officialAction: 'Terkin, hak sahibinin ve resmî sistemin işlemiyle tamamlanır; uygulama kendiliğinden kayıt kaldıramaz.',
  },
  {
    id: 'usufruct-easement',
    title: 'İntifa ve irtifak hakkı',
    shortTitle: 'Ayni hak',
    description: 'Kullanım, geçit veya benzeri ayni hakların tesisi ve terkini için hazırlık yapın.',
    category: 'SECURITY',
    caseType: 'OTHER',
    duration: 'Uzman kontrollü',
    audience: 'Malik + hak sahibi',
    steps: ['Hak türü ve kapsam', 'Taraf/taşınmaz', 'Süre ve bedel', 'Takyidat/öncelik', 'Tescil/terkin'],
    documents: ['Hak talebi ve kapsam açıklaması', 'Güncel tapu kaydı', 'Taraf kimlik/temsil belgeleri', 'Varsa kroki veya teknik belge'],
    risks: ['Hakkın kapsamının belirsizliği', 'Paydaş onaylarının eksikliği', 'Teknik güzergâh veya süre uyuşmazlığı'],
    officialAction: 'Hakkın kurulması veya kaldırılması yalnız resmî tescil/terkinle sonuç doğurur.',
  },
  {
    id: 'inheritance-transfer',
    title: 'Miras intikali',
    shortTitle: 'Miras',
    description: 'Muris adına kayıtlı taşınmazların mirasçılara intikal hazırlığını yönetin.',
    category: 'INHERITANCE',
    caseType: 'INHERITANCE',
    duration: '6 aşama',
    audience: 'Mirasçılar',
    steps: ['Muris ve mirasçı tespiti', 'Mirasçılık belgesi', 'Taşınmaz listesi', 'Vergi ilişiği', 'Başvuru/tebligat', 'Tescil/pay kontrolü'],
    documents: ['Mirasçılık belgesi', 'Muris ve mirasçı kimlik bilgileri', 'Taşınmaz kayıtları', 'Veraset ve intikal vergi hazırlığı', 'DASK bilgisi gereken taşınmazlar'],
    risks: ['Eksik mirasçı', 'Pay oranı hatası', 'Vergi ilişiği veya tebligat sorunu', 'Mirasçılık belgesinin güncel olmaması'],
    officialAction: 'Noter/mahkeme, GİB ve Tapu Müdürlüğü belgeleri resmî kaynaktan alınır ve doğrulanır.',
  },
  {
    id: 'inheritance-partition',
    title: 'Miras paylaşımı ve taksim',
    shortTitle: 'Taksim',
    description: 'Mirasçılar arasındaki taşınmaz paylaşımını pay, mutabakat ve tescil düzeyinde hazırlayın.',
    category: 'INHERITANCE',
    caseType: 'INHERITANCE',
    duration: 'Uzman kontrollü',
    audience: 'Tüm mirasçılar',
    steps: ['Mirasçı/pay doğrulama', 'Taşınmaz envanteri', 'Paylaşım mutabakatı', 'Vergi ve değer', 'Resmî işlem', 'Yeni pay kontrolü'],
    documents: ['Mirasçılık belgesi', 'Tüm taşınmaz kayıtları', 'Paylaşım/taksim belgesi', 'Taraf kimlik ve temsil belgeleri'],
    risks: ['Tüm mirasçıların katılımı', 'Paylaşım değeri ve denklik', 'Kısıtlı veya küçük mirasçı', 'Şekil şartı'],
    officialAction: 'Paylaşım belgesinin şekli ve tescil yolu noter/avukat/Tapu Müdürlüğüyle doğrulanmalıdır.',
  },
  {
    id: 'joint-to-shared',
    title: 'Elbirliğinden paylı mülkiyete geçiş',
    shortTitle: 'Paylı mülkiyet',
    description: 'Elbirliği mülkiyetindeki taşınmazı paylı mülkiyete dönüştürme hazırlığını izleyin.',
    category: 'INHERITANCE',
    caseType: 'INHERITANCE',
    duration: '5 aşama',
    audience: 'Ortaklar/mirasçılar',
    steps: ['Ortakların tespiti', 'Payların hesaplanması', 'Tebligat/muvafakat', 'Başvuru', 'Yeni kayıt kontrolü'],
    documents: ['Mirasçılık veya ortaklık dayanağı', 'Güncel tapu kaydı', 'Taraf adres/tebligat bilgileri', 'Varsa muvafakat veya karar'],
    risks: ['Pay oranı uyuşmazlığı', 'Eksik taraf veya tebligat', 'Kısıtlı ortak'],
    officialAction: 'Uygulanacak usul somut kayda göre Tapu Müdürlüğünce belirlenir.',
  },
  {
    id: 'condominium',
    title: 'Kat mülkiyeti tesisi',
    shortTitle: 'Kat mülkiyeti',
    description: 'Tamamlanan yapıda bağımsız bölüm tescili için teknik ve idari evrakı izleyin.',
    category: 'REGISTRATION',
    caseType: 'CORRECTION',
    duration: 'Teknik süreç',
    audience: 'Malik/paydaşlar',
    steps: ['Yapı ve ruhsat bilgisi', 'İskân kontrolü', 'Proje/bağımsız bölümler', 'Yönetim planı', 'Kadastro/Tapu başvurusu'],
    documents: ['Yapı kullanma izin belgesi', 'Onaylı mimari proje', 'Yönetim planı', 'Bağımsız bölüm listesi', 'DASK bilgileri'],
    risks: ['Proje-fiilî durum farkı', 'Eksik iskân veya teknik belge', 'Pay/bağımsız bölüm eşleşme hatası'],
    officialAction: 'Belediye, kadastro/LİHKAB ve Tapu Müdürlüğü teknik belgeleri esas alınır.',
  },
  {
    id: 'construction-servitude',
    title: 'Kat irtifakı tesisi',
    shortTitle: 'Kat irtifakı',
    description: 'Yapım sürecindeki projede arsa payı ve bağımsız bölüm irtifakı hazırlığını takip edin.',
    category: 'REGISTRATION',
    caseType: 'OTHER',
    duration: 'Teknik süreç',
    audience: 'Arsa maliki/yüklenici',
    steps: ['Parsel/pay kontrolü', 'Proje ve ruhsat', 'Arsa payı listesi', 'Yönetim planı', 'Tescil kontrolü'],
    documents: ['Onaylı proje ve ruhsat', 'Arsa payı/bağımsız bölüm listesi', 'Yönetim planı', 'Taraf/temsil evrakı'],
    risks: ['Arsa payı hatası', 'Proje/ruhsat uyumsuzluğu', 'Temsil ve yüklenici yetkisi'],
    officialAction: 'Teknik dosya ve resmî tescil ilgili kurumların incelemesine tabidir.',
  },
  {
    id: 'type-change',
    title: 'Cins değişikliği',
    shortTitle: 'Cins değişikliği',
    description: 'Arsa, bina veya kullanım niteliği değişikliğinin teknik tespit ve tescilini hazırlayın.',
    category: 'REGISTRATION',
    caseType: 'CORRECTION',
    duration: 'Teknik süreç',
    audience: 'Malik',
    steps: ['Mevcut kayıt', 'Yeni fiilî durum', 'Belediye belgeleri', 'Zemin/ölçüm dosyası', 'Tescil doğrulaması'],
    documents: ['Güncel tapu kaydı', 'Yapı ruhsatı/iskan', 'Teknik ölçüm veya zemin tespit evrakı', 'Malik/temsil belgeleri'],
    risks: ['Fiilî durumun ruhsata aykırılığı', 'Eksik teknik dosya', 'Adres ve nitelik uyuşmazlığı'],
    officialAction: 'Belediye ve kadastro/LİHKAB teknik kontrolü olmadan tamamlanamaz.',
  },
  {
    id: 'identity-correction',
    title: 'Tapu kaydında düzeltme',
    shortTitle: 'Kayıt düzeltme',
    description: 'Malik kimliği, adres, yüzölçümü veya kayıt hatasının dayanaklarını düzenleyin.',
    category: 'REGISTRATION',
    caseType: 'CORRECTION',
    duration: '4 aşama',
    audience: 'Malik/ilgilisi',
    steps: ['Hata türü', 'Mevcut kayıt', 'Doğru bilgi/dayanak', 'Başvuru ve sonuç kontrolü'],
    documents: ['Güncel tapu kayıt örneği', 'Kimlik/nüfus veya kurum dayanağı', 'Varsa teknik rapor/kroki', 'Talep açıklaması'],
    risks: ['Yanlış kayıtla yanlış kişiyi eşleştirme', 'Teknik düzeltmenin hukuki düzeltme sanılması', 'Eksik dayanak'],
    officialAction: 'Düzeltme usulü hatanın türüne göre Tapu Müdürlüğü veya yetkili yargı/kurumca belirlenir.',
  },
  {
    id: 'parcel-operations',
    title: 'İfraz, tevhit ve parsel işlemleri',
    shortTitle: 'Parsel işlemi',
    description: 'Parsel ayırma/birleştirme sürecinde belediye ve kadastro adımlarını izleyin.',
    category: 'REGISTRATION',
    caseType: 'OTHER',
    duration: 'Teknik süreç',
    audience: 'Malik/paydaşlar',
    steps: ['İmar uygunluğu', 'Malik/pay kontrolü', 'Harita/teknik dosya', 'Belediye kararı', 'Kadastro ve tescil'],
    documents: ['Güncel tapu ve çap', 'İmar durumu', 'Yetkili harita mühendisi dosyası', 'Belediye encümen/kurum kararı', 'Taraf muvafakatleri'],
    risks: ['İmar planına aykırılık', 'Paydaş muvafakati', 'Yola terk/alan değişimi', 'Teknik dosya hatası'],
    officialAction: 'Belediye, kadastro ve Tapu Müdürlüğü onayı gerektirir; panel teknik karar vermez.',
  },
  {
    id: 'family-home',
    title: 'Aile konutu kontrolü ve şerhi',
    shortTitle: 'Aile konutu',
    description: 'Aile konutu niteliği, eş bilgisi, şerh ve rıza gereksinimini erken kontrol edin.',
    category: 'SPECIAL',
    caseType: 'OTHER',
    duration: 'Hukuk kontrolü',
    audience: 'Malik + eş',
    steps: ['Medeni hâl/yerleşim', 'Taşınmaz eşleştirme', 'Mevcut şerh', 'Eş rızası veya başvuru', 'Kayıt doğrulaması'],
    documents: ['Güncel tapu kaydı', 'Yerleşim/aile durumu dayanakları', 'Eş kimlik ve iletişim bilgisi', 'Varsa muvafakat veya resmî başvuru belgesi'],
    risks: ['Eş rızasının gerekli olduğu işlemi atlamak', 'Yanlış taşınmaz/adres eşleştirmesi', 'Muvafakat şekli'],
    officialAction: 'Aile konutu değerlendirmesi ve şerh/rıza işlemi hukuk uzmanı ile resmî makamca doğrulanır.',
  },
  {
    id: 'guardianship',
    title: 'Velayet, vesayet ve kısıtlı taraf işlemi',
    shortTitle: 'Vesayet',
    description: 'Küçük veya kısıtlı taraf bulunan işlemlerde karar, izin ve temsil zincirini hazırlayın.',
    category: 'SPECIAL',
    caseType: 'OTHER',
    duration: 'Mahkeme kontrollü',
    audience: 'Veli/vasi/kayyım',
    steps: ['Taraf statüsü', 'Temsilci ve karar', 'Mahkeme izin kapsamı', 'Çıkar çatışması', 'Resmî işlem'],
    documents: ['Nüfus/kimlik bilgileri', 'Vasi/kayyım kararı', 'Gerekli mahkeme izinleri', 'Taşınmaz ve işlem değer evrakı'],
    risks: ['İzin kapsamı veya süresi', 'Çıkar çatışması', 'Fiil ehliyeti hakkında varsayım', 'Eksik mahkeme kararı'],
    officialAction: 'AI ehliyet veya izin kararı vermez; mahkeme ve hukuk uzmanı kontrolü zorunludur.',
  },
  {
    id: 'foreign-party-sale',
    title: 'Yabancı taraflı taşınmaz satışı',
    shortTitle: 'Yabancı satış',
    description: 'Yabancı alıcı veya satıcı bulunan işlemde kimlik, tercüme, değerleme ve ödeme dallarını izleyin.',
    category: 'SPECIAL',
    caseType: 'SALE',
    duration: 'Uzman kontrollü',
    audience: 'Yabancı alıcı/satıcı',
    steps: ['Pasaport/YKN/VKN', 'Edinim uygunluğu', 'Değerleme ve ödeme belgeleri', 'Tercüman/temsil', 'Başvuru ve tescil', 'İşlem sonrası arşiv'],
    documents: ['Pasaport ve gerektiğinde tercüme', 'YKN/VKN bilgisi', 'Gerekli değerleme raporu', 'Döviz alım/ödeme belgeleri gereken işlem dalında', 'Apostilli veya onaylı temsil belgesi'],
    risks: ['Taşınmaz edinim kısıtı', 'Belge tercüme/apostil zinciri', 'Döviz ve ödeme belgesi', 'Vatandaşlık amacıyla işlemde özel kurallar'],
    officialAction: 'Güncel TKGM yabancı işlem talimatı ve yetkili uzman kontrolü esas alınır.',
  },
  {
    id: 'corporate-party',
    title: 'Şirketin taraf olduğu tapu işlemi',
    shortTitle: 'Tüzel kişi',
    description: 'Şirket, vakıf veya dernek taraflı işlemde güncel temsil ve imza yetkisini izleyin.',
    category: 'SPECIAL',
    caseType: 'SALE',
    duration: '5 aşama',
    audience: 'Tüzel kişi + temsilci',
    steps: ['Tüzel kişi kaydı', 'Temsil ve imza yetkisi', 'Karar/onay', 'Taşınmaz ve işlem', 'Başvuru/tescil'],
    documents: ['Güncel sicil/MERSİS bilgisi', 'Temsil ve imza yetkisi dayanağı', 'Gerekli şirket/organ kararı', 'Vergi numarası ve kimlikler', 'Taşınmaz evrakı'],
    risks: ['Süresi dolmuş veya kapsam dışı yetki', 'Birlikte imza şartı', 'Şirket kararı gereksinimi', 'Gerçek faydalanıcı belirsizliği'],
    officialAction: 'Temsil yetkisi güncel resmî sicil ve kurum belgeleriyle doğrulanır.',
  },
  {
    id: 'power-of-attorney',
    title: 'Vekâletli tapu işlemi hazırlığı',
    shortTitle: 'Vekâlet',
    description: 'Vekâletname kapsamı, süre, kimlik, yabancı belge ve azil durumunu kontrol edin.',
    category: 'SPECIAL',
    caseType: 'OTHER',
    duration: 'Hukuk kontrolü',
    audience: 'Asıl + vekil',
    steps: ['Belge kaynağı', 'Taraf kimlik eşleştirme', 'İşlem/taşınmaz kapsamı', 'Süre/azil/tercüme', 'Resmî doğrulama'],
    documents: ['Noter veya yetkili makam vekâletnamesi', 'Asıl/vekil kimlik bilgileri', 'Yabancı belgeyse apostil/tercüme zinciri', 'Güncel taşınmaz kaydı'],
    risks: ['Genel ifadeyle özel yetki gereksinimi', 'Azil veya süre', 'Kimlik/taşınmaz uyuşmazlığı', 'Yabancı belgenin şekli'],
    officialAction: 'Panel vekâletname üretmez; belgenin geçerliliği noter/Tapu Müdürlüğü ve hukuk uzmanıyla doğrulanır.',
  },
];

export const DEED_QUICK_TYPES: Array<{
  id: string;
  label: string;
  description: string;
  type: DeedCaseType;
}> = [
  { id: 'sale', label: 'Satış / devir', description: 'Satıcıdan alıcıya standart devir', type: 'SALE' },
  { id: 'purchase', label: 'Alıcı takibi', description: 'Alıcı adına inceleme ve satın alma', type: 'PURCHASE' },
  { id: 'mortgage', label: 'İpotek', description: 'İpotek tesisi veya terkini', type: 'MORTGAGE' },
  { id: 'inheritance', label: 'Miras', description: 'İntikal, paylaşım veya pay dönüşümü', type: 'INHERITANCE' },
  { id: 'correction', label: 'Tescil / düzeltme', description: 'Kayıt, cins veya kat mülkiyeti işlemi', type: 'CORRECTION' },
  { id: 'other', label: 'Diğer işlem', description: 'Hibe, parsel, vekâlet veya özel durum', type: 'OTHER' },
];

export function getDeedProcessGuide(id: string | null) {
  return id ? DEED_PROCESS_GUIDES.find((guide) => guide.id === id) || null : null;
}
